### ISSUE TITLE
Could not find OOD data files

### ISSUE THREAD

**Issue by veeraelluru** [ishalyminov/ood_robust_hcn#2]
https://github.com/ishalyminov/ood_robust_hcn/blob/master/babi_tools/ood_augmentation.py

load_ood() function reads following files. But, those files are not present in the repo.

twitter_ood_positive.txt
twitter_ood_negative.txt
twitter_ood_breakdown.txt
reddit_ood_breakdown.txt
stanford_ood.txt
dstc1_ood.txt
frames_ood.txt

--Veera.

**Comment by ishalyminov** [comment]
Hi Veera, nice catch, thanks!
As far as I remember, those files are supposed to be generated using the `mining_*.ipynb` notebooks in the repo root. Please let me know if it works for you, and I'll update the repo accordingly.

**Comment by veeraelluru** [comment]
Hi Ishalyminov,

Thank you for your quick reply. Yes, mining_*.ipynb files generates those files. But, nlp_utils.py expects "bad_words.txt" for profanity_check. This file is missing. Could you please point if available.

--Veera.

**Comment by ishalyminov** [comment]
Thanks!
This is my bad - I guess it's just this file: https://www.cs.cmu.edu/~biglou/resources/bad-words.txt, forgot to mention it anywhere.

**Comment by veeraelluru** [comment]
Thank again. Got bad words from above link.

Another data sets missing are

- /home/t-igshal/data/dstc1

- generating stanford_ood.txt file

I also have another request. Could you please point source code for following paper if you have.

https://arxiv.org/pdf/1905.10247.pdf

--Veera.

**Comment by ishalyminov** [comment]
Hmm, looks like I have to do a proper run of the script..
For that paper, we didn't release the code but the data is available here: https://github.com/sungjinl/icassp2019-ood-dataset

**Comment by veeraelluru** [comment]
Thank for pointing the data.

**Comment by veeraelluru** [comment]
I got dstc1 data from following github page.

https://github.com/ananda621/gitlfs/find/master

**Comment by ishalyminov** [comment]
I re-ran all the scripts and updated the repo. The repo should now be self-contained - please follow the updated README.md to run the code.
